<a href="https://colab.research.google.com/github/vedant-sangrame/Machine-Learning/blob/main/Prac5_ML_ASSIGNMNET1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vedant Sangrame (CS23163)**

**ASSIGNMENT - 1**

**Aim: To implement the Random forest algorithm and evaluate the model performance using appropriate metrics.**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = "/content/drive/MyDrive/ML_dataset/Gaming and Mental Health - Gaming and Mental Health.csv"
df = pd.read_csv(path)
df.head(5)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [ ]:
df.describe()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
count,1000.000000,1000.000000,1000.000000,754.000000,674.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.475000,6.151400,5.738100,2.518037,5.394659,1.513400,6.945900,3.872000,7.654500,105.219730,5.796000
std,4.116105,2.867194,1.441213,0.872312,2.898742,1.432212,1.805027,2.091409,3.751954,113.886768,3.775532
min,13.000000,0.500000,3.000000,1.010000,1.000000,0.000000,0.700000,1.000000,0.000000,0.100000,1.000000
25%,18.000000,4.100000,4.800000,1.760000,3.000000,0.400000,5.700000,2.000000,5.000000,32.592500,3.000000
50%,20.000000,6.000000,5.700000,2.530000,5.000000,1.100000,7.000000,4.000000,8.000000,66.405000,5.000000
75%,22.000000,8.025000,6.600000,3.280000,8.000000,2.100000,8.200000,5.000000,10.400000,126.242500,8.000000
max,35.000000,15.100000,9.000000,4.000000,10.000000,8.900000,11.500000,10.000000,16.700000,499.270000,20.000000

In [ ]:
df.shape

(1000, 27)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   object
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   object
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object
 5   primary_game                      1000 non-null   object
 6   gaming_platform                   1000 non-null   object
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object
 9   sleep_disruption_frequency        1000 non-null   object
 10  academic_work_performance         1000 non-null   object
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   object
 14  mood_swing_frequency              1000 non-null   object
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(11)
memory usage: 176.9+ KB

In [ ]:
df.columns

Index(['record_id', 'age', 'gender', 'daily_gaming_hours', 'game_genre',
       'primary_game', 'gaming_platform', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'academic_work_performance', 'grades_gpa',
       'work_productivity_score', 'mood_state', 'mood_swing_frequency',
       'withdrawal_symptoms', 'loss_of_other_interests',
       'continued_despite_problems', 'eye_strain', 'back_neck_pain',
       'weight_change_kg', 'exercise_hours_weekly', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'monthly_game_spending_usd',
       'years_gaming', 'gaming_addiction_risk_level'],
      dtype='object')

In [ ]:
df.isnull()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().any()

record_id                           False
age                                 False
gender                              False
daily_gaming_hours                  False
game_genre                          False
primary_game                        False
gaming_platform                     False
sleep_hours                         False
sleep_quality                       False
sleep_disruption_frequency          False
academic_work_performance           False
grades_gpa                           True
work_productivity_score              True
mood_state                          False
mood_swing_frequency                False
withdrawal_symptoms                 False
loss_of_other_interests             False
continued_despite_problems          False
eye_strain                          False
back_neck_pain                      False
weight_change_kg                    False
exercise_hours_weekly               False
social_isolation_score              False
face_to_face_social_hours_weekly    False
monthly_game_spending_usd           False
years_gaming                        False
gaming_addiction_risk_level         False
dtype: bool

In [ ]:
df.isnull().any().any()

np.True_

In [ ]:
df.isnull().sum()

record_id                             0
age                                   0
gender                                0
daily_gaming_hours                    0
game_genre                            0
primary_game                          0
gaming_platform                       0
sleep_hours                           0
sleep_quality                         0
sleep_disruption_frequency            0
academic_work_performance             0
grades_gpa                          246
work_productivity_score             326
mood_state                            0
mood_swing_frequency                  0
withdrawal_symptoms                   0
loss_of_other_interests               0
continued_despite_problems            0
eye_strain                            0
back_neck_pain                        0
weight_change_kg                      0
exercise_hours_weekly                 0
social_isolation_score                0
face_to_face_social_hours_weekly      0
monthly_game_spending_usd             0
years_gaming                          0
gaming_addiction_risk_level           0
dtype: int64

In [ ]:
df[df.isnull().any(axis = 1)]

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate
7,GD0008,28,Female,10.3,Mobile Games,Clash of Clans,Console,5.2,Fair,Sometimes,...,True,True,True,2.4,5.6,6,0.2,299.28,13,Severe
8,GD0009,18,Male,1.4,Mobile Games,Genshin Impact,PC,8.9,Poor,Always,...,False,False,False,0.1,10.1,1,12.9,49.40,6,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,GD0996,15,Female,8.6,Strategy,Age of Empires,PC,4.1,Very Poor,Always,...,True,True,True,1.9,7.5,6,2.4,426.54,3,Severe
996,GD0997,18,Male,5.4,MMO,Elder Scrolls Online,Multi-platform,6.5,Fair,Never,...,False,True,False,2.1,7.7,1,10.9,83.71,7,Low
997,GD0998,23,Male,7.3,RPG,Skyrim,PC,3.9,Insomnia,Rarely,...,False,False,True,0.5,8.1,5,6.7,88.60,5,High
998,GD0999,18,Male,3.1,Strategy,StarCraft II,Console,8.2,Fair,Sometimes,...,False,False,False,0.8,8.4,1,12.7,22.02,8,Low
999,GD1000,29,Male,3.5,RPG,Cyberpunk 2077,Multi-platform,7.4,Good,Sometimes,...,False,False,False,0.0,9.3,2,10.9,25.20,19,Low

In [ ]:
X = df.drop(columns=['gaming_addiction_risk_level'])
y = df['gaming_addiction_risk_level']

In [ ]:
X.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,False,True,True,False,6.8,3.7,7,1.3,383.70,3
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,False,0.4,8.5,2,10.7,46.64,1
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,True,False,True,1.8,7.1,5,3.2,100.81,6
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,True,False,True,True,0.2,5.2,4,9.1,51.60,7
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,False,0.5,6.1,4,4.5,32.57,1

In [ ]:
X = pd.get_dummies(X, dtype = int)

In [ ]:
X.head()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,withdrawal_symptoms,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,...,mood_state_Excited,mood_state_Irritable,mood_state_Normal,mood_state_Restless,mood_state_Withdrawn,mood_swing_frequency_Daily,mood_swing_frequency_Never,mood_swing_frequency_Often,mood_swing_frequency_Rarely,mood_swing_frequency_Sometimes
0,17,11.1,3.7,1.25,NaN,True,False,True,True,False,...,0,0,0,0,0,0,1,0,0,0
1,21,3.0,7.2,3.75,2.0,False,False,False,False,False,...,0,1,0,0,0,0,0,1,0,0
2,23,7.6,4.4,NaN,9.0,True,True,True,False,True,...,0,1,0,0,0,0,0,0,1,0
3,20,7.2,5.1,1.62,2.0,True,True,False,True,True,...,0,0,0,0,1,1,0,0,0,0
4,18,6.8,3.4,2.44,NaN,True,False,False,False,False,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
X.shape

(1000, 1084)

In [ ]:
X.columns

Index(['age', 'daily_gaming_hours', 'sleep_hours', 'grades_gpa',
       'work_productivity_score', 'withdrawal_symptoms',
       'loss_of_other_interests', 'continued_despite_problems', 'eye_strain',
       'back_neck_pain',
       ...
       'mood_state_Excited', 'mood_state_Irritable', 'mood_state_Normal',
       'mood_state_Restless', 'mood_state_Withdrawn',
       'mood_swing_frequency_Daily', 'mood_swing_frequency_Never',
       'mood_swing_frequency_Often', 'mood_swing_frequency_Rarely',
       'mood_swing_frequency_Sometimes'],
      dtype='object', length=1084)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state = 42)

X_train.shape, X_test.shape

((700, 1084), (300, 1084))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, n_jobs = -1, max_depth = 5, oob_score = True, random_state = 42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_pred = rf_classifier.predict(X_test)
print(y_pred)

['High' 'High' 'Low' 'Moderate' 'Severe' 'Low' 'Low' 'Low' 'Low' 'Severe'
 'Low' 'Severe' 'Low' 'High' 'High' 'Moderate' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Moderate' 'Low' 'Low'
 'High' 'Low' 'High' 'Low' 'Low' 'Severe' 'High' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Severe' 'Low' 'Severe' 'Low' 'Low' 'Low' 'Severe' 'Low'
 'Low' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'Severe'
 'Low' 'Low' 'Low' 'Low' 'Severe' 'Low' 'Moderate' 'High' 'Low' 'Low'
 'Moderate' 'Low' 'Low' 'Low' 'Low' 'Low' 'Severe' 'Low' 'Low' 'Low'
 'High' 'Moderate' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Moderate'
 'Low' 'Low' 'Low' 'High' 'Low' 'Moderate' 'Moderate' 'Low' 'Low' 'Low'
 'High' 'Severe' 'Low' 'Low' 'Moderate' 'High' 'High' 'High' 'Low' 'Low'
 'Low' 'High' 'Low' 'Severe' 'Low' 'Low' 'High' 'Low' 'Moderate' 'Severe'
 'High' 'Severe' 'Low' 'Moderate' 'High' 'Low' 'High' 'Low' 'Moderate'
 'Severe' 'Severe' 'Severe' 'Low' 'Severe' 'Moderate' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Severe' 'Moderate' 'Low' 'Severe' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low'
 'Low' 'Severe' 'Low' 'Low' 'Severe' 'Low' 'Low' 'Low' 'Moderate' 'Low'
 'Low' 'Severe' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Severe' 'Low' 'Low'
 'Severe' 'High' 'Low' 'High' 'High' 'Low' 'High' 'Low' 'Low' 'Low' 'Low'
 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low'
 'High' 'Low' 'Low' 'Low' 'Low' 'High' 'Severe' 'Low' 'Moderate' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Severe' 'Low'
 'Severe' 'Moderate' 'Moderate' 'Low' 'Low' 'Low' 'Moderate' 'Low' 'Low'
 'Moderate' 'Low' 'Low' 'Low' 'Moderate' 'Low' 'Severe' 'High' 'Low'
 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Moderate' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Moderate' 'Moderate' 'Severe' 'Severe' 'Low'
 'Low' 'Low' 'Low' 'Moderate' 'Severe' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Severe' 'High' 'Low' 'Severe' 'Severe' 'Low' 'Low' 'Severe' 'Low'
 'Moderate' 'Moderate' 'High' 'Low' 'Low' 'Low' 'Low' 'High' 'Low'
 'Severe' 'High' 'Low' 'Severe' 'Low' 'Severe' 'Low']

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
print('Confusion Matrix')
cm = confusion_matrix(y_pred, y_test)
print(confusion_matrix(y_pred, y_test))

Confusion Matrix
[[ 21   0   8   8]
 [  9 148  38   1]
 [ 17   0   4   7]
 [  5   0   0  34]]

In [ ]:
print('Accuracy Score')
print(accuracy_score(y_pred, y_test))

Accuracy Score
0.69

In [ ]:
rf_classifier.oob_score_

0.6914285714285714

In [ ]:
print('Classification Report')
print(classification_report (y_pred, y_test))

Classification Report
              precision    recall  f1-score   support

        High       0.40      0.57      0.47        37
         Low       1.00      0.76      0.86       196
    Moderate       0.08      0.14      0.10        28
      Severe       0.68      0.87      0.76        39

    accuracy                           0.69       300
   macro avg       0.54      0.58      0.55       300
weighted avg       0.80      0.69      0.73       300

In [ ]:
rf = RandomForestClassifier(random_state = 42, n_jobs = -1)

params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator = rf, param_grid = params, cv = 4, n_jobs = -1, verbose = 1, scoring = 'accuracy')
grid_search.fit(X_train, y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_score_

np.float64(0.6671428571428571)

In [ ]:
print(grid_search.best_params_)

{'max_depth': 20, 'min_samples_leaf': 5, 'n_estimators': 50}